"""Generator tests for tools/generate_map.py.

Asserts the spec's Representative mappings table and the pinned
v16.0.0 key count against the live pinned dataset. Run with:

    python3 test/test_generate.py
"""

import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import generate_map as gen  # noqa: E402


def u(*codepoints):
    return "".join(chr(cp) for cp in codepoints)


def entry(unified, name, category="Smileys & Emotion"):
    return {
        "unified": unified,
        "short_name": name,
        "short_names": [name],
        "category": category,
        "skin_variations": {},
    }


# Every row of the spec's "Representative mappings" table (lines 193-206).
REPRESENTATIVE_MAPPINGS = {
    u(0x1F600): "grinning",
    u(0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F467): "man-woman-girl",
    u(0x1F1FA, 0x1F1F8): "flag-us",
    u(0x1F1EC, 0x1F1E7): "flag-gb",
    u(0x1F1E8, 0x1F1F3): "flag-cn",
    u(0x1F44D, 0x1F3FB): "+1",
    u(0x1F44B, 0x1F3FD): "wave",
    u(0x2764, 0xFE0F): "heart",
    u(0x0031, 0xFE0F, 0x20E3): "one",
    u(0x002A, 0xFE0F, 0x20E3): "keycap_star",
    u(0x2639, 0xFE0F): "white_frowning_face",
    u(0x00A9, 0xFE0F): "copyright",
}


class GenerateMapTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.entries = gen.load_dataset()
        cls.map = gen.build_map(cls.entries)

    def test_pinned_key_count(self):
        self.assertEqual(len(self.map), 3781)

    def test_representative_mappings(self):
        for sequence, name in REPRESENTATIVE_MAPPINGS.items():
            self.assertEqual(
                self.map.get(sequence),
                name,
                "mapping for %s" % " ".join("%04X" % ord(c) for c in sequence),
            )

    def test_dataset_has_no_collisions(self):
        # build_map aborts on a collision, so a successful build proves zero.
        self.assertEqual(len(self.map), 3781)
        self.assertEqual(gen.build_map(self.entries), self.map)

    def test_collision_aborts(self):
        entries = [entry("1F600", "grinning"), entry("1F600", "other_name")]
        with self.assertRaises(SystemExit):
            gen.build_map(entries)

    def test_empty_name_aborts(self):
        with self.assertRaises(SystemExit):
            gen.build_map([entry("1F600", "")])

    def test_bad_name_aborts(self):
        with self.assertRaises(SystemExit):
            gen.build_map([entry("1F600", "Bad Name!")])

    def test_unparseable_sequence_aborts(self):
        with self.assertRaises(SystemExit):
            gen.build_map([entry("ZZZZ", "grinning")])

    def test_header_contract(self):
        lines = gen.render_vim(self.map).splitlines()
        self.assertEqual(lines[0], "scriptencoding utf-8")
        self.assertIn("Generated by tools/generate_map.py, do not edit.", lines[1])
        header = "\n".join(lines[:10])
        self.assertIn('" SOURCE_TAG: v16.0.0', header)
        self.assertIn('" Entries: 3781', header)

    def test_longest_key_is_ten_code_points(self):
        # Keys are literal emoji strings; Python len is the code point count.
        self.assertEqual(max(len(k) for k in self.map), 10)

    def test_names_are_shortcode_safe(self):
        import re

        for name in self.map.values():
            self.assertRegex(name, r"^[a-z0-9_+-]+$")

    def test_render_is_deterministic(self):
        first = gen.render_vim(self.map)
        second = gen.render_vim(self.map)
        self.assertEqual(first, second)
        self.assertEqual(first, gen.render_vim(gen.build_map(self.entries)))

    def test_check_reports_drift(self):
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "input.json"
            output = Path(tmp) / "data.vim"
            source.write_text(json.dumps([entry("1F600", "grinning")]), encoding="utf-8")
            output.write_text("stale\n", encoding="utf-8")
            self.assertEqual(
                gen.main(["--input", str(source), "--output", str(output), "--check"]),
                1,
            )
            self.assertEqual(
                gen.main(["--input", str(source), "--output", str(output)]), 0
            )
            self.assertEqual(
                gen.main(["--input", str(source), "--output", str(output), "--check"]),
                0,
            )


if __name__ == "__main__":
    unittest.main()
