" Define a dictionary mapping emoji to their corresponding text labels
let s:emoji_to_label = {
\ '😀': 'grinning_face',
\ '😃': 'smiling_face_with_open_mouth',
\ '😄': 'smiling_face_with_open_mouth_and_smiling_eyes',
\ '😁': 'beaming_face_with_smiling_eyes',
\ '😆': 'grinning_squinting_face',
\ '😅': 'grinning_face_with_sweat',
\ '😂': 'face_with_tears_of_joy',
\ '🤣': 'rolling_on_the_floor_laughing',
\ '😊': 'smiling_face_with_smiling_eyes',
\ '😇': 'smiling_face_with_halo',
\ '🙂': 'slightly_smiling_face',
\ '🙃': 'upside_down_face',
\ '😉': 'winking_face',
\ '😌': 'relieved_face',
\ '😍': 'heart_eyes',
\ '😘': 'face_blowing_a_kiss',
\ '😗': 'kissing_face',
\ '😙': 'kissing_face_with_smiling_eyes',
\ '😚': 'kissing_face_with_closed_eyes',
\ '😋': 'face_savoring_food',
\ '😛': 'face_with_tongue',
\ '😝': 'squinting_face_with_tongue',
\ '😜': 'winking_face_with_tongue',
\ '🤪': 'zany_face',
\ '🤨': 'face_with_raised_eyebrow',
\ '🧐': 'face_with_monocle',
\ '🤓': 'nerd_face',
\ '😎': 'smiling_face_with_sunglasses',
\ '🤩': 'star_struck',
\ '🥳': 'partying_face',
\ '😏': 'smirking_face',
\ '😒': 'unamused_face',
\ '😞': 'disappointed_face',
\ '😔': 'pensive_face',
\ '😟': 'worried_face',
\ '😕': 'confused_face',
\ '🙁': 'slightly_frowning_face',
\ '☹️': 'frowning_face',
\ '😣': 'persevering_face',
\ '😖': 'confounded_face',
\ '😫': 'tired_face',
\ '😩': 'weary_face',
\ '🥺': 'pleading_face',
\ '😢': 'crying_face',
\ '😭': 'loudly_crying_face',
\ '😤': 'face_with_steam_from_nose',
\ '😠': 'angry_face',
\ '😡': 'pouting_face',
\ '🤬': 'face_with_symbols_on_mouth',
\ '🤯': 'exploding_head',
\ '😳': 'flushed_face',
\ '🥵': 'hot_face',
\ '🥶': 'cold_face',
\ '😱': 'face_screaming_in_fear',
\ '😨': 'fearful_face',
\ '😰': 'anxious_face_with_sweat',
\ '😥': 'sad_but_relieved_face',
\ '😓': 'downcast_face_with_sweat',
\ '🤗': 'hugging_face',
\ '🤔': 'thinking_face',
\ '🤭': 'face_with_hand_over_mouth',
\ '🤫': 'shushing_face',
\ '🤥': 'lying_face',
\ '😶': 'face_without_mouth',
\ '😐': 'neutral_face',
\ '😑': 'expressionless_face',
\ '😬': 'grimacing_face',
\ '🙄': 'face_with_rolling_eyes',
\ '😯': 'hushed_face',
\ '😦': 'frowning_face_with_open_mouth',
\ '😧': 'anguished_face',
\ '😮': 'face_with_open_mouth',
\ '😲': 'astonished_face',
\ '🥱': 'yawning_face',
\ '😴': 'sleeping_face',
\ '🤤': 'drooling_face',
\ '😪': 'sleepy_face',
\ '😵': 'dizzy_face',
\ '🤐': 'zipped_mouth_face',
\ '🥴': 'woozy_face',
\ '🤢': 'nauseated_face',
\ '🤮': 'face_vomiting',
\ '🤧': 'sneezing_face',
\ '😷': 'face_with_medical_mask',
\ '🤒': 'face_with_thermometer',
\ '🤕': 'face_with_head_bandage',
\ '🤑': 'money_mouth_face',
\ '🤠': 'cowboy_hat_face',
\ '😈': 'smiling_face_with_horns',
\ '👿': 'angry_face_with_horns',
\ '💀': 'skull',
\ '☠️': 'skull_and_crossbones',
\ '💩': 'pile_of_poo',
\ '🤡': 'clown_face',
\ '👹': 'ogre',
\ '👺': 'goblin',
\ '👻': 'ghost',
\ '👽': 'alien',
\ '👾': 'alien_monster',
\ '🤖': 'robot',
\ }

" Loop through the dictionary and replace each emoji in the buffer
function! ConvertEmojiToText()
    for [emoji, label] in items(s:emoji_to_label)
        execute '%s/'.emoji.'/::'.label.'::/g'
    endfor
endfunction

" Map the function to a key, e.g., F5
nnoremap <F5> :call ConvertEmojiToText()<CR>

