#!/usr/bin/env python3
"""Generate autoload/emoji_to_text/data.vim from iamcal/emoji-data.

Build-time only; the plugin itself ships the generated map and needs no
Python or network at runtime. Standard library only.
"""

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
CACHE_DIR = TOOLS_DIR / ".cache"

SOURCE_TAG = "v16.0.0"
SOURCE_COMMIT = "2771d0b1b3af25c069086e68e38f901c3dda8bdf"
SOURCE_SHA256 = "1d602e65be88772bf8cc368ce16b855d719eeddbafe128d471b80203f494d29f"
SOURCE_DATE = "2026-10-05"
GENERATOR_VERSION = "0.1.0"
SOURCE_URL = (
    "https://raw.githubusercontent.com/iamcal/emoji-data/"
    + SOURCE_COMMIT
    + "/emoji.json"
)
DEFAULT_OUTPUT = "autoload/emoji_to_text/data.vim"
NAME_PATTERN = re.compile(r"^[a-z0-9_+-]+$")


def parse_sequence(sequence):
    """Split a dataset sequence on '-' and read each token as hex."""
    try:
        return tuple(int(token, 16) for token in sequence.split("-"))
    except ValueError as exc:
        raise ValueError(
            "Unparseable code point in sequence %r: %s" % (sequence, exc)
        ) from exc


def sequence_to_string(sequence):
    """Turn a dataset sequence such as '1F468-200D-1F469' into characters."""
    return "".join(chr(codepoint) for codepoint in parse_sequence(sequence))


def canonical_name(entry):
    """short_name, except Flags where the first flag- alias wins."""
    if entry.get("category") == "Flags":
        for alias in entry.get("short_names", []):
            if alias.startswith("flag-"):
                return alias
    return entry["short_name"]


def build_map(entries):
    """Build the fully-qualified sequence -> bare shortcode mapping."""
    mapping = {}
    collisions = {}

    def register(sequence, name):
        if not name:
            raise SystemExit("Empty name for sequence %r" % sequence)
        if not NAME_PATTERN.match(name):
            raise SystemExit(
                "Name %r for sequence %r has characters outside [a-z0-9_+-]"
                % (name, sequence)
            )
        try:
            key = sequence_to_string(sequence)
        except ValueError as exc:
            raise SystemExit("Unparseable sequence %r: %s" % (sequence, exc)) from exc
        existing = mapping.get(key)
        if existing is not None and existing != name:
            collisions.setdefault(key, {existing}).add(name)
        mapping[key] = name

    for entry in entries:
        if entry.get("category") == "Component":
            continue
        name = canonical_name(entry)
        register(entry["unified"], name)
        for variation in entry.get("skin_variations", {}).values():
            register(variation["unified"], name)

    if collisions:
        details = "\n".join(
            "%s -> %s" % (seq, ", ".join(sorted(names)))
            for seq, names in sorted(collisions.items())
        )
        raise SystemExit("Collisions detected:\n" + details)

    return mapping


def default_meta():
    return {
        "source_url": SOURCE_URL,
        "source_tag": SOURCE_TAG,
        "source_commit": SOURCE_COMMIT,
        "sha256": SOURCE_SHA256,
        "refreshed": SOURCE_DATE,
        "generator": GENERATOR_VERSION,
    }


def vim_escape(value):
    return "'" + value.replace("'", "''") + "'"


def render_vim(mapping, meta=None):
    """Render the data module. Deterministic for a given mapping."""
    meta = meta or default_meta()
    lines = [
        "scriptencoding utf-8",
        '" Generated by tools/generate_map.py, do not edit.',
        '" Source: %s' % meta["source_url"],
        '" SOURCE_TAG: %s' % meta["source_tag"],
        '" SOURCE_COMMIT: %s' % meta["source_commit"],
        '" SHA256: %s' % meta["sha256"],
        '" Refreshed: %s' % meta["refreshed"],
        '" Entries: %d' % len(mapping),
        '" Generator: %s' % meta["generator"],
        "",
        "let s:map = {",
    ]
    items = sorted(
        mapping.items(), key=lambda item: tuple(ord(char) for char in item[0])
    )
    last = len(items) - 1
    for index, (sequence, name) in enumerate(items):
        suffix = "," if index < last else ""
        lines.append(
            "\\ %s: %s%s" % (vim_escape(sequence), vim_escape(name), suffix)
        )
    lines.extend(
        [
            "\\ }",
            "",
            "function! emoji_to_text#data#map() abort",
            "  return s:map",
            "endfunction",
            "",
        ]
    )
    return "\n".join(lines)


def load_dataset(input_path=None):
    """Load entries from a local JSON file, a verified cache, or the pin.

    The cache is keyed by SOURCE_COMMIT, so bumping the pin misses it and
    forces a fresh verified download.
    """
    if input_path is not None:
        return json.loads(Path(input_path).read_bytes().decode("utf-8"))

    cache_path = CACHE_DIR / ("emoji-%s.json" % SOURCE_COMMIT)
    if cache_path.exists():
        raw = cache_path.read_bytes()
        if hashlib.sha256(raw).hexdigest() == SOURCE_SHA256:
            return json.loads(raw.decode("utf-8"))

    with urllib.request.urlopen(SOURCE_URL) as response:
        raw = response.read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(
            "sha256 mismatch: expected %s, got %s" % (SOURCE_SHA256, digest)
        )
    try:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        cache_path.write_bytes(raw)
    except OSError:
        pass  # the cache is an optimization; a read-only checkout still works
    return json.loads(raw.decode("utf-8"))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", help="local emoji.json (skips the network)")
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed output differs",
    )
    args = parser.parse_args(argv)

    entries = load_dataset(args.input)
    mapping = build_map(entries)
    content = render_vim(mapping)
    output = Path(args.output)

    if args.check:
        existing = output.read_text(encoding="utf-8") if output.exists() else None
        if existing != content:
            print(
                "%s is out of date; run make generate" % output,
                file=sys.stderr,
            )
            return 1
        print("%s is up to date (%d entries)" % (output, len(mapping)))
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print("Wrote %s (%d entries)" % (output, len(mapping)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
